<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
//decide which logo to show
$requestDomain = $_SERVER['HTTP_HOST'];
$title = '';

switch (true) {
	case (strpos($requestDomain, 'lay-z-spa') !== false):
		$title   = 'Lay-Z-Spa Maintenance';
		break;
	case (strpos($requestDomain, 'bestway') !== false):
		$title   = 'Bestway Store Maintenance';
		break;
	default:
		$title   = 'Maintenance';
}
?>

<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title><?= $title ?></title>
    <base href="<?= $this->getViewFileUrl() ?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="*"/>
    <link rel="stylesheet" href="css/styles.css" type="text/css" />
    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
</head>
<body>
    <main class="page-main">
        <?php require_once $contentTemplate; ?>
    </main>
</body>
</html>
